version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: yoga-postgres
    environment:
      POSTGRES_DB: yoga
      POSTGRES_USER: psycho
      POSTGRES_PASSWORD: dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U psycho -d yoga"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: