// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/lessions": {
    params: {};
  };
  "/admin/lessons-list": {
    params: {};
  };
  "/admin/actions": {
    params: {};
  };
  "/admin/teachers": {
    params: {};
  };
  "/admin/posters": {
    params: {};
  };
  "/admin/notices": {
    params: {};
  };
  "/admin/admin-users": {
    params: {};
  };
  "/admin/locations": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin" | "/admin/dashboard" | "/admin/lessions" | "/admin/lessons-list" | "/admin/actions" | "/admin/teachers" | "/admin/posters" | "/admin/notices" | "/admin/admin-users" | "/admin/locations" | "/admin/users" | "/*";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/";
  };
  "components/AdminLayout.tsx": {
    id: "components/AdminLayout";
    page: "/admin" | "/admin/dashboard" | "/admin/lessions" | "/admin/lessons-list" | "/admin/actions" | "/admin/teachers" | "/admin/posters" | "/admin/notices" | "/admin/admin-users" | "/admin/locations" | "/admin/users";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin/dashboard";
  };
  "routes/admin/lessions.tsx": {
    id: "routes/admin/lessions";
    page: "/admin/lessions";
  };
  "routes/admin/lessons-list.tsx": {
    id: "routes/admin/lessons-list";
    page: "/admin/lessons-list";
  };
  "routes/admin/actions.tsx": {
    id: "routes/admin/actions";
    page: "/admin/actions";
  };
  "routes/admin/teachers.tsx": {
    id: "routes/admin/teachers";
    page: "/admin/teachers";
  };
  "routes/admin/posters.tsx": {
    id: "routes/admin/posters";
    page: "/admin/posters";
  };
  "routes/admin/notices.tsx": {
    id: "routes/admin/notices";
    page: "/admin/notices";
  };
  "routes/admin/admin-users.tsx": {
    id: "routes/admin/admin-users";
    page: "/admin/admin-users";
  };
  "routes/admin/locations.tsx": {
    id: "routes/admin/locations";
    page: "/admin/locations";
  };
  "routes/admin/users.tsx": {
    id: "routes/admin/users";
    page: "/admin/users";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};